import { supabase } from './supabaseClient'

function normalize(p) {
  return { ...p, name: p.title || '', category: p.categories?.name || '—' }
}

export async function fetchAllProducts() {
  const { data, error } = await supabase
    .from('products')
    .select('*, categories(id, name)')
    .order('title')
  return { data: (data || []).map(normalize), error }
}

export async function fetchCategories() {
  const { data, error } = await supabase.from('categories').select('id, name').order('name')
  return { data: data || [], error }
}

// Never send `id` (GENERATED BY DEFAULT) or `is_available` (computed column).
export async function createProduct(fields) {
  const { data, error } = await supabase
    .from('products')
    .insert({
      title:       fields.title.trim(),
      description: fields.description?.trim() || null,
      category_id: fields.category_id ? Number(fields.category_id) : null,
      price:       Number(fields.price)        || 0,
      stock:       parseInt(fields.stock, 10)  || 0,
      image:       fields.image?.trim()        || null,
    })
    .select('id')
    .single()
  if (error) throw error
  return data
}

// Two-step: insert product → get id → bulk-insert variants.
export async function createProductWithVariants(fields, variants) {
  const { data: product, error: productError } = await supabase
    .from('products')
    .insert({
      title:       fields.title.trim(),
      description: fields.description?.trim() || null,
      category_id: fields.category_id ? Number(fields.category_id) : null,
      image:       fields.image?.trim()        || null,
      price:       0,
      stock:       0,
    })
    .select('id')
    .single()
  if (productError) throw productError

  const rows = variants
    .filter(v => v.size.trim())
    .map(v => ({
      product_id: product.id,
      size:       v.size.trim(),
      price:      Math.round(Number(v.price)   || 0),  // bigint column — must be integer
      quantity:   parseInt(v.quantity, 10)     || 0,
    }))

  if (rows.length > 0) {
    const { error: variantError } = await supabase.from('product-variants').insert(rows)
    if (variantError) {
      // Clean up orphaned product so the DB stays consistent
      await supabase.from('products').delete().eq('id', product.id)
      throw variantError
    }
  }
  return product
export async function fetchAllProducts() {
  return supabase
    .from('products')
    .select('*')
    .order('title')
}

export async function updateProduct(id, updates) {
  return supabase
    .from('products')
    .update(updates)
    .eq('id', id)
    .select('*')
    .single()
}

export async function toggleProductFeatured(id, featured) {
  return updateProduct(id, { featured })
}
